### ISSUE TITLE
Not stable issue: Sometimes an error occurs after starting or restarting the pipeline that transfers data from the Zendesk Source to the Destination

### ISSUE THREAD

**Issue by SerhiiSpivak** [conduitio-labs/conduit-connector-zendesk#18]
### Bug description

Sometimes an error occurs after starting or restarting the pipeline that transfers data from the Zendesk Source to the Destination

The issue isn't stable 

```
 2022-09-28T12:51:14+00:00 ERR destination acker node stopped before processing all messages error="nacked 1 messages when stopping destination acker node, some nacks failed: no DLQ handler configured" component=DestinationAckerNode node_id=2dd849e9-d967-403f-9105-ad3e98f61468-acker pipeline_id=0f70b007-80a1-4010-b1ac-f7b800c43191 stack=[{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).teardown","line":182},{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/source_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceAckerNode)).registerNackHandler.func1","line":118}] 2022-09-28T12:51:14+00:00 ERR node stopped error="node 2dd849e9-d967-403f-9105-ad3e98f61468-acker stopped with error: failed to receive ack: %!w(<nil>)" component=pipeline.Service node_id=2dd849e9-d967-403f-9105-ad3e98f61468-acker stack=[{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/lifecycle.go","func":"[github.com/conduitio/conduit/pkg/pipeline.(*Service](http://github.com/conduitio/conduit/pkg/pipeline.(*Service)).runPipeline.func1","line":411},{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).worker","line":131}]
 ```

### Steps to reproduce

1. Create a Pipeline 
2. Create Zendesk Destination connector and the Destination connector (for example NATS PubSub Destination connector), config:

```yaml
version: 1.0                  

pipelines:                    
  pipeline1:                   
    status: stopped             
    name: pipeline1             
    description: desc           
    connectors:                 
      con1:                 
        type: source            
        plugin: standalone:zendesk    
        name: zendesk-source             
        settings:              
          zendesk.domain: <domain> 
         zendesk.userName: <user name in zendesk>
          zendesk.apiToken: <zendesk api token>
          pollingPeriod:
      con2:
        type: destination
        plugin: standalone:nats-pubsub
        name: nats-pubsub-DESTINATION
        settings:
           urls: <NATS connection URL> 
          subject: sbj
           connectionName:
           nkeyPath:
           credentialsFilePath:
           tls.clientCertPath:
           tls.clientPrivateKeyPath:
           tls.rootCACertPath:
           maxReconnects:
           reconnectWait:
```
3. Start (or restart)  the pipeline 
4. Get an error
```
2022-09-28T12:51:14+00:00 ERR destination acker node stopped before processing all messages error="nacked 1 messages when stopping destination acker node, some nacks failed: no DLQ handler configured" component=DestinationAckerNode node_id=2dd849e9-d967-403f-9105-ad3e98f61468-acker pipeline_id=0f70b007-80a1-4010-b1ac-f7b800c43191 stack=[{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).teardown","line":182},{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/source_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceAckerNode)).registerNackHandler.func1","line":118}] 2022-09-28T12:51:14+00:00 ERR node stopped error="node 2dd849e9-d967-403f-9105-ad3e98f61468-acker stopped with error: failed to receive ack: %!w(<nil>)" component=pipeline.Service node_id=2dd849e9-d967-403f-9105-ad3e98f61468-acker stack=[{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/lifecycle.go","func":"[github.com/conduitio/conduit/pkg/pipeline.(*Service](http://github.com/conduitio/conduit/pkg/pipeline.(*Service)).runPipeline.func1","line":411},{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).worker","line":131}]
```

### Version

v0.3.0-nightly.20220927
