### ISSUE TITLE
An error occurs when trying to transfer data from the Zendesk source connector to the Postgres Destination connector 

### ISSUE THREAD

**Issue by SerhiiSpivak** [conduitio-labs/conduit-connector-zendesk#20]
### Bug description

The user creates the Zendesk Sorce connector and the Postgres Destination connector; then the user starts the pipeline -> the system returns an error

```
2022-09-29T11:52:08+00:00 ERR destination acker node stopped before processing all messages error="nacked 1 messages when stopping destination acker node, some nacks failed: no DLQ handler configured" component=DestinationAckerNode node_id=c1885e93-fe4c-4c7f-b9e5-ff454ee7a6c3-acker pipeline_id=9b8daf3c-a063-42ff-8d1d-9b79279ebf4e stack=[{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).teardown","line":182},{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/source_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceAckerNode)).registerNackHandler.func1","line":118}] 2022-09-29T11:52:08+00:00 ERR node stopped error="node 3aaee7d8-ad65-4ae9-8066-90310f92a31d-acker stopped with error: failed to receive ack: error receiving ack: failed to get key: json: cannot unmarshal number into Go value of type map[string]interface {}" component=pipeline.Service node_id=3aaee7d8-ad65-4ae9-8066-90310f92a31d-acker stack=[{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/lifecycle.go","func":"[github.com/conduitio/conduit/pkg/pipeline.(*Service](http://github.com/conduitio/conduit/pkg/pipeline.(*Service)).runPipeline.func1","line":411},{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).worker","line":131},{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/connector/destination.go","func":"[github.com/conduitio/conduit/pkg/connector.(*destination](http://github.com/conduitio/conduit/pkg/connector.(*destination)).Ack","line":247},{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/plugin/builtin/v1/destination.go","func":"[github.com/conduitio/conduit/pkg/plugin/builtin/v1.(*destinationPluginAdapter](http://github.com/conduitio/conduit/pkg/plugin/builtin/v1.(*destinationPluginAdapter)).Ack","line":138}]
```

### Steps to reproduce

1. Create the pipeline
2. Create Zendesk source connector and Postgres destination connector (see below config):
```yaml
version: 1.0                  

pipelines:                    
  pipeline1:                   
    status: stopped             
    name: pipeline1             
    description: desc           
    connectors:                 
      con1:                 
        type: source            
        plugin: standalone:zendesk    
        name: zendesk-source             
        settings:              
          zendesk.domain: <domain> 
          zendesk.userName: <user name in zendesk>
          zendesk.apiToken: <zendesk api token>
          pollingPeriod:
      con2:
        type: destination
        plugin: builtin:postgres
        name: postgres-destination
        settings:
           url: postgresql://postgres:12345@localhost:5432/postgres 
           table: test_table
           keyColumn: <column name >
```
3. Start the pipeline 
4. Get an error
```
2022-09-29T11:52:08+00:00 ERR destination acker node stopped before processing all messages error="nacked 1 messages when stopping destination acker node, some nacks failed: no DLQ handler configured" component=DestinationAckerNode node_id=c1885e93-fe4c-4c7f-b9e5-ff454ee7a6c3-acker pipeline_id=9b8daf3c-a063-42ff-8d1d-9b79279ebf4e stack=[{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).teardown","line":182},{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/source_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*SourceAckerNode)).registerNackHandler.func1","line":118}] 2022-09-29T11:52:08+00:00 ERR node stopped error="node 3aaee7d8-ad65-4ae9-8066-90310f92a31d-acker stopped with error: failed to receive ack: error receiving ack: failed to get key: json: cannot unmarshal number into Go value of type map[string]interface {}" component=pipeline.Service node_id=3aaee7d8-ad65-4ae9-8066-90310f92a31d-acker stack=[{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/lifecycle.go","func":"[github.com/conduitio/conduit/pkg/pipeline.(*Service](http://github.com/conduitio/conduit/pkg/pipeline.(*Service)).runPipeline.func1","line":411},{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).worker","line":131},{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/connector/destination.go","func":"[github.com/conduitio/conduit/pkg/connector.(*destination](http://github.com/conduitio/conduit/pkg/connector.(*destination)).Ack","line":247},{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/plugin/builtin/v1/destination.go","func":"[github.com/conduitio/conduit/pkg/plugin/builtin/v1.(*destinationPluginAdapter](http://github.com/conduitio/conduit/pkg/plugin/builtin/v1.(*destinationPluginAdapter)).Ack","line":138}]
```

### Version

v0.3.0-nightly.20220927
