### ISSUE TITLE
An error occurs when trying to transfer data from the Zendesk source to the Materialize Destination 

### ISSUE THREAD

**Issue by SerhiiSpivak** [conduitio-labs/conduit-connector-zendesk#21]
### Bug description

The user creates the Zendesk Sorce connector and the Materialize Destination connector; then the user starts the pipeline -> the system returns an error

```
2022-09-29T11:33:01+00:00 ERR error writing record error="route snapshot: failed to exec insert: ERROR: Expected an expression, found right parenthesis (SQLSTATE 42601)" component=plugin connector_id=f5f6a705-02e4-44ba-8c89-07c89599b143 plugin_name=conduit-connector-materialize record_position="{\"mode\":\"snapshot\",\"last_modified_time\":\"2022-09-27T10:35:17Z\",\"id\":1}" 2022-09-29T11:33:01+00:00 ERR destination acker node stopped before processing all messages error="nacked 3 messages when stopping destination acker node, some nacks failed: no DLQ handler configured\nanother message failed to be acked/nacked\nanother message failed to be acked/nacked" component=DestinationAckerNode node_id=f5f6a705-02e4-44ba-8c89-07c89599b143-acker pipeline_id=9b8daf3c-a063-42ff-8d1d-9b79279ebf4e stack=[{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).teardown","line":182}]
```

### Steps to reproduce

1. Create the pipeline
2. Create Zendesk source connector and Materialize destination connector (see below config):
```yaml
version: 1.0                  

pipelines:                    
  pipeline1:                   
    status: stopped             
    name: pipeline1             
    description: desc           
    connectors:                 
      con1:                 
        type: source            
        plugin: standalone:zendesk    
        name: zendesk-source             
        settings:              
          zendesk.domain: <domain> 
          zendesk.userName: <user name in zendesk>
          zendesk.apiToken: <zendesk api token>
          pollingPeriod:
      con2:
        type: destination
        plugin: standalone:materialize
        name: materialize-destination
        settings:
           url: <the connection URL for Materialize instance>
           table: test_table
           key: <column name >
```
3. Start the pipeline
4. Get an error

```
2022-09-29T11:33:01+00:00 ERR error writing record error="route snapshot: failed to exec insert: ERROR: Expected an expression, found right parenthesis (SQLSTATE 42601)" component=plugin connector_id=f5f6a705-02e4-44ba-8c89-07c89599b143 plugin_name=conduit-connector-materialize record_position="{\"mode\":\"snapshot\",\"last_modified_time\":\"2022-09-27T10:35:17Z\",\"id\":1}" 2022-09-29T11:33:01+00:00 ERR destination acker node stopped before processing all messages error="nacked 3 messages when stopping destination acker node, some nacks failed: no DLQ handler configured\nanother message failed to be acked/nacked\nanother message failed to be acked/nacked" component=DestinationAckerNode node_id=f5f6a705-02e4-44ba-8c89-07c89599b143-acker pipeline_id=9b8daf3c-a063-42ff-8d1d-9b79279ebf4e stack=[{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).teardown","line":182}]
```

### Version

v0.3.0-nightly.20220927
