### ISSUE TITLE
An error occurs when trying to transfer data from the Zendesk source to the Vitess Destination 

### ISSUE THREAD

**Issue by SerhiiSpivak** [conduitio-labs/conduit-connector-zendesk#22]
### Bug description

The user creates the Zendesk Sorce connector and the Vitess Destination connector; then the user starts the pipeline -> the system returns an error

```
2022-09-29T12:19:26+00:00 ERR error writing record error="insert record: exec upsert: Code: INVALID_ARGUMENT\nsyntax error at position 619\n" component=plugin connector_id=1c1a4163-fbb2-467c-9cdc-4b6e655f2931 plugin_name=conduit-connector-vitess record_position="{\"mode\":\"snapshot\",\"last_modified_time\":\"2022-09-27T10:35:17Z\",\"id\":1}" 2022-09-29T12:19:26+00:00 ERR destination acker node stopped before processing all messages error="nacked 2 messages when stopping destination acker node, some nacks failed: no DLQ handler configured\nanother message failed to be acked/nacked" component=DestinationAckerNode node_id=1c1a4163-fbb2-467c-9cdc-4b6e655f2931-acker pipeline_id=37b8481b-b840-495f-8246-0db5235ba47d stack=[{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).teardown","line":182}]
```

### Steps to reproduce

1. Create the pipeline
2. Create Zendesk source connector and Vitess destination connector (see below config):
```yaml
version: 1.0                  

pipelines:                    
  pipeline1:                   
    status: stopped             
    name: pipeline1             
    description: desc           
    connectors:                 
      con1:                 
        type: source            
        plugin: standalone:zendesk    
        name: zendesk-source             
        settings:              
          zendesk.domain: <domain> 
          zendesk.userName: <user name in zendesk>
          zendesk.apiToken: <zendesk api token>
          pollingPeriod:
      con2:
        type: destination
        plugin: standalone:vitess
        name: vitess-destination
        settings:
           address: <hostname:port>
           table: test_table
           keyColumn: <column name >
           keyspace:  <specifies a VTGate keyspace>
           username:
           password:
           tabletType:
```
3. Start the pipeline
4. Get an error
```
2022-09-29T12:19:26+00:00 ERR error writing record error="insert record: exec upsert: Code: INVALID_ARGUMENT\nsyntax error at position 619\n" component=plugin connector_id=1c1a4163-fbb2-467c-9cdc-4b6e655f2931 plugin_name=conduit-connector-vitess record_position="{\"mode\":\"snapshot\",\"last_modified_time\":\"2022-09-27T10:35:17Z\",\"id\":1}" 2022-09-29T12:19:26+00:00 ERR destination acker node stopped before processing all messages error="nacked 2 messages when stopping destination acker node, some nacks failed: no DLQ handler configured\nanother message failed to be acked/nacked" component=DestinationAckerNode node_id=1c1a4163-fbb2-467c-9cdc-4b6e655f2931-acker pipeline_id=37b8481b-b840-495f-8246-0db5235ba47d stack=[{"file":"/home/serhiispivak/go/src/github.com/conduit/pkg/pipeline/stream/destination_acker.go","func":"[github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode](http://github.com/conduitio/conduit/pkg/pipeline/stream.(*DestinationAckerNode)).teardown","line":182}]
```

### Version

v0.3.0-nightly.20220927
