### ISSUE TITLE
Data from DATABASE (Oracle, Vitess, Postgres, and others) isn’t transferred to Zendesk

### ISSUE THREAD

**Issue by SerhiiSpivak** [conduitio-labs/conduit-connector-zendesk#23]
### Bug description

The user creates the Sorce connector (DATABASE; for example Vitess) and the Zendesk Destination connector; then the user starts the pipeline -> Data from DATABASE isn’t transferred to Zendesk

This issue reproduces for Source connectors that use DATABASE  (Oracle, Vitess, Postgres, and others)

### Steps to reproduce

1. Create the pipeline
2. Create  Source connector (for example Vitess) and Zendesk destination connector (see below config):
```yaml
version: 1.0                  

pipelines:                    
  pipeline1:                   
    status: stopped             
    name: pipeline1             
    description: desc           
    connectors:                 
      con1:                 
        type: source            
        plugin: standalone:vitess  
        name: vitess-source    
        settings:
           address: <hostname:port>
           table: test_table
           keyspace:  <specifies a VTGate keyspace>
           orderingColumn: <column name >
           keyColumn: 
           columns:
           username:
           password:
           tabletType:
           batchSize:         
      con2:
        type: destination
        plugin: standalone:zendesk
        name: zendesk-destination
        settings:              
          zendesk.domain: <domain> 
          zendesk.userName: <user name in zendesk>
          zendesk.apiToken: <zendesk api token>
          bufferSize:
          maxRetries:
```
3. Start the pipeline
4. Data isn't transferred to Zendesk Destination; any error doesn't occur  

**Additional info:** This issue reproduces for Source connectors that use DATABASE  (Oracle, Vitess, Postgres, and others)
    

### Version

v0.3.0-nightly.20220927
